name: Create and publish image

on:
  push:

env:
  IMAGE_NAME: vwc-strapi

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: graysonlee123/vwc-strapi:latest
